<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommentsMgt.Domain\CommentsMgt.Domain.csproj" />
    <ProjectReference Include="..\CommentsMgt.DTO\CommentsMgt.DTOs.csproj" />
  </ItemGroup>

</Project>
